name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 
          cache: 'pip'  # Enable pip caching

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run Lint
        run: pylint webserpent

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Enable pip caching

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest  # Explicitly install pytest

      - name: Run tests
        run: pytest

  publish-test:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'  # Enable pip caching

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Get current version and set test version
        run: |
          CURRENT_VERSION=$(grep -Po "(?<=version = \"|version=')[^\"']*" setup.py pyproject.toml 2>/dev/null || echo "0.0.0")
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "TEST_VERSION=${CURRENT_VERSION}.dev${GITHUB_RUN_NUMBER}+pr${PR_NUMBER}" >> $GITHUB_ENV

      - name: Update version for test
        run: |
          if [ -f "setup.py" ]; then
            sed -i "s/version=['\"][^'\"]*['\"]/version='${{ env.TEST_VERSION }}'/" setup.py
          fi
          if [ -f "pyproject.toml" ]; then
            sed -i "s/version = \"[^\"]*\"/version = \"${{ env.TEST_VERSION }}\"/" pyproject.toml
          fi

      - name: Build package
        run: python -m build

      - name: Publish to GitHub Packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python -m twine upload --repository-url https://maven.pkg.github.com/${{ github.repository }} \
            --username ${{ github.actor }} \
            --password ${{ secrets.GITHUB_TOKEN }} \
            dist/*