name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Run Lint
        run: |
          source .venv/bin/activate
          pylint webserpent

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest

  publish-test:
    needs: [lint, test]
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install build twine

      - name: Get current version and set test version
        run: |
          CURRENT_VERSION=$(grep -Po "(?<=version = \"|version=')[^\"']*" setup.py pyproject.toml 2>/dev/null || echo "0.0.0")
          echo "TEST_VERSION=${CURRENT_VERSION}.dev${GITHUB_RUN_NUMBER}+pr${GITHUB_EVENT_NUMBER}" >> $GITHUB_ENV

      - name: Update version for test
        run: |
          if [ -f "setup.py" ]; then
            sed -i "s/version=['\"][^'\"]*['\"]/version='${TEST_VERSION}'/" setup.py
          fi
          if [ -f "pyproject.toml" ]; then
            sed -i "s/version = \"[^\"]*\"/version = \"${TEST_VERSION}\"/" pyproject.toml
          fi

      - name: Build package
        run: python -m build

      - name: Configure .pypirc for GitHub Packages
        run: |
          echo "[distutils]" > ~/.pypirc
          echo "index-servers = github" >> ~/.pypirc
          echo "[github]" >> ~/.pypirc
          echo "repository: https://upload.github.com/${{ github.repository }}" >> ~/.pypirc
          echo "username: __token__" >> ~/.pypirc
          echo "password: ${{ secrets.GITHUB_TOKEN }}" >> ~/.pypirc

      - name: Publish to GitHub Packages
        run: twine upload --repository github dist/*
